### PR TITLE
Update to compile against Parsec 3.1.8

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by bgamari** [comment]
Is there a reason why Travis is configured for this repository despite there being no tests?

**Comment by bgamari** [comment]
Ping.

**Comment by vincenthz** [comment]
Good point, I've added a .travis for automatic compilation-testing.
I've applied your fix but added a compatibility with old parsec instead of just putting the upper bound on 3.1. also I'm allergic to upper bounds, so I've removed that as well.

**Comment by vincenthz** [comment]
Thanks

**Pull request closed without merging**
